name: vector_shield
description: "IoT-Based Train Cargo Load Monitoring and Clearance System"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.7.2 <4.0.0"  # Ensure compatibility with Dart 3.7

dependencies:
  flutter:
    sdk: flutter
  google_maps_flutter: ^2.6.0
  fl_chart: ^0.70.2
  cupertino_icons: ^1.0.8
  firebase_core: ^3.9.0
  firebase_auth: ^5.3.4
  http: ^1.2.1
  flutter_dotenv: ^5.2.1
  geolocator: ^13.0.4
  permission_handler: ^11.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - .env
